FROM arm32v7/maven:3.6-jdk-11 AS build

WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn -f /app/pom.xml clean package


FROM arm32v7/openjdk:11

ARG JAR_FILE=/app/target/job-scraper-spring-server-0.0.1-SNAPSHOT.jar

COPY --from=build ${JAR_FILE} job-scraper-spring-server.jar

ENV NEXT_CLIENT_HOST="192.168.0.8"

ENTRYPOINT ["java","-Dsun.net.http.allowRestrictedHeaders=true","-jar","/job-scraper-spring-server.jar"]
